// DO NOT EDIT MANUALY UNLESS YOU KNOW WHAT YOU ARE DOING 
// This files is autogenerated on build and by app-generator 
// load all router admin endpoint for every module registered to this project 


const routes = []
;

export default routes;